server:
  shutdown: graceful

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:8380
  cloud:
    config:
      uri: http://localhost:8380
      fail-fast: true
  lifecycle:
    timeout-per-shutdown-phase: 20s
  gateway:
    default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      - AddResponseHeader=X-Content-Type-Options, nosniff
      - AddResponseHeader=X-Frame-Options, DENY
      - AddResponseHeader=X-XSS-Protection, 1; mode=block
      - AddResponseHeader=Strict-Transport-Security, max-age=31536000; includeSubDomains
      - AddResponseHeader=Cache-Control, no-store, no-cache, must-revalidate
      - AddResponseHeader=Pragma, no-cache
      - RemoveResponseHeader=Server
      - SecureHeaders
    globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins:
            - "http://localhost:4200"
            - "https://yourdomain.com"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders:
            - Authorization
            - Content-Type
            - Accept
            - Origin
            - X-Requested-With
          exposedHeaders:
            - Authorization
            - Link
          allowCredentials: true
          maxAge: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    health-check-url-path: /actuator/health
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO
    reactor.netty: INFO
